site_name: Rewards Sharing Simulation Engine - Docs
nav:
        - Home: index.md
        - Setup: setup.md
        - Configuration: configuration.md
        - Metrics: metrics.md
        - Examples: examples.md
        - Output: output.md
theme: readthedocs
