site_name: Cardano Pooling Simulator - Docs
nav:
        - Home: index.md
        - Overview: overview.md
        - Setup: setup.md
        - Configuation: configuration.md
        - Examples: examples.md 
theme: readthedocs
