site_name: Cardano Pooling Simulator - Docs
nav:
        - Home: index.md
        - Setup: setup.md
        - Configuration: configuration.md
        - Examples: examples.md
        - Output: output.md
theme: readthedocs
